services:
  php-84-fpm:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/project

    depends_on:
      - mysql

  nginx-php-84:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/opt/project/public
      - ./src:/opt/project/src
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php-84-fpm

  node-react:
    image: node:20
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev -- --host"

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
